In [129]:
import pandas as pd 
import numpy as np
import math
import csv

#**Importing the dataset**

In [130]:
data = pd.read_csv("train.csv")
x_df = data.loc[:,["MSSubClass","LotArea","OverallQual","OverallCond","YearBuilt","1stFlrSF","2ndFlrSF","GrLivArea","GarageArea","YrSold"]]
x = x_df.values 
y = data.iloc[:,-1].values



##**features scalling**

In [131]:
scal_fact = x_df.max().values
x = x/scal_fact
x_train = x  
y_train = y
y_train=np.ones((len(y),1))
y_train = y.reshape(len(y),1)

[[208500]
 [181500]
 [223500]
 ...
 [266500]
 [142125]
 [147500]]
1460
10


#**training the model**

##**A) training the linear regression model**

In [119]:
x_train1 = np.c_[np.ones(len(x_train)),x_train]
count = 0
i = []
theta1 = np.random.rand(len(x_train1[0]),1)
lr = 0.1
loss = []
saving_cnt=0

with open("theta_linear_reg", 'w', newline='') as myfile:
     wr = csv.writer(myfile, quoting=csv.QUOTE_ALL)
     while (True):
      y_pred = np.matmul(x_train1,theta1)
      grad = np.matmul(np.transpose(x_train1) , np.subtract(y_pred,y_train))/len(x_train)
      theta1 = np.subtract(theta1,lr*grad)
      loss.append(np.sum(np.square(np.subtract(y_pred,y_train)))/(len(x_train1)))
      i.append(count)
      count+=1
      print(f"at iteration{count} loss = {loss[-1]}")
      saving_cnt +=1
      if(saving_cnt%1000==0):
        wr.writerow(theta1)




Streaming output truncated to the last 5000 lines.
at iteration4321475 loss = 1435348978.4039712
at iteration4321476 loss = 1435348968.793517
at iteration4321477 loss = 1435348959.183065
at iteration4321478 loss = 1435348949.5726144
at iteration4321479 loss = 1435348939.962165
at iteration4321480 loss = 1435348930.3517177
at iteration4321481 loss = 1435348920.7412713
at iteration4321482 loss = 1435348911.1308265
at iteration4321483 loss = 1435348901.5203831
at iteration4321484 loss = 1435348891.9099414
at iteration4321485 loss = 1435348882.299501
at iteration4321486 loss = 1435348872.6890626
at iteration4321487 loss = 1435348863.078625
at iteration4321488 loss = 1435348853.4681892
at iteration4321489 loss = 1435348843.8577552
at iteration4321490 loss = 1435348834.247322
at iteration4321491 loss = 1435348824.636891
at iteration4321492 loss = 1435348815.026461
at iteration4321493 loss = 1435348805.4160328
at iteration4321494 loss = 1435348795.8056056
at iteration4321495 loss = 1435348786

KeyboardInterrupt: ignored

##**B) training the 2nd-degree non-linear model**

In [6]:
x_train2 = np.c_[np.ones(len(x_train)),x_train,np.square(x_train)]
prev_loss = -math.inf 
current_loss = math.inf
count = 0
i = []
theta2 = np.random.rand(len(x_train2[0]),1)
lr = 0.1
loss = []
saving_cnt=0


with open("theta_2nd-degree_reg", 'w', newline='') as myfile:
     wr = csv.writer(myfile, quoting=csv.QUOTE_ALL)
     while (True):
      y_pred = np.matmul(x_train2,theta2)
      grad = np.matmul(np.transpose(x_train2) , np.subtract(y_pred,y_train))/len(x_train2)
      theta2 = np.subtract(theta2,lr*grad)
      loss.append(np.sum(np.square(np.subtract(y_pred,y_train)))/(len(x_train2)))
      i.append(count)
      print(f"at iteration {count} loss = {loss[-1]}")
      count+=1
      saving_cnt +=1
      if(saving_cnt%1000==0):
        wr.writerow(theta2)


Streaming output truncated to the last 5000 lines.
at iteration 2522364 loss = 980810069.5210553
21
at iteration 2522365 loss = 980810069.5206499
21
at iteration 2522366 loss = 980810069.5202447
21
at iteration 2522367 loss = 980810069.5198398
21
at iteration 2522368 loss = 980810069.5194346
21
at iteration 2522369 loss = 980810069.5190293
21
at iteration 2522370 loss = 980810069.5186243
21
at iteration 2522371 loss = 980810069.5182191
21
at iteration 2522372 loss = 980810069.5178139
21
at iteration 2522373 loss = 980810069.5174088
21
at iteration 2522374 loss = 980810069.5170039
21
at iteration 2522375 loss = 980810069.5165989
21
at iteration 2522376 loss = 980810069.5161934
21
at iteration 2522377 loss = 980810069.5157882
21
at iteration 2522378 loss = 980810069.5153832
21
at iteration 2522379 loss = 980810069.5149782
21
at iteration 2522380 loss = 980810069.5145729
21
at iteration 2522381 loss = 980810069.514168
21
at iteration 2522382 loss = 980810069.5137625
21
at iteration 252238

KeyboardInterrupt: ignored

##**C) training the 3rd-degree non-linear model**


In [9]:
x_train3 = np.c_[np.ones(len(x_train)),x_train,np.square(x_train),np.power(x_train,3)]
prev_loss = -math.inf 
current_loss = math.inf
count = 0
i = []
theta3 = np.random.rand(len(x_train3[0]),1)
lr = 0.1
loss = []
saving_cnt=0

with open("theta_3rd-degree_reg", 'w', newline='') as myfile:
     wr = csv.writer(myfile, quoting=csv.QUOTE_ALL)
     while (True):
      y_pred = np.matmul(x_train3,theta3)
      grad = np.matmul(np.transpose(x_train3) , np.subtract(y_pred,y_train))/len(x_train3)
      theta3 = np.subtract(theta3,lr*grad)
      loss.append(np.sum(np.square(np.subtract(y_pred,y_train)))/(len(x_train3)))
      i.append(count)
      count+=1
      print(f"at iteration {count} loss = {loss[-1]}")
      saving_cnt +=1
      if(saving_cnt%1000==0):
        wr.writerow(theta3)


print(loss)

Streaming output truncated to the last 5000 lines.
at iteration 6272819 loss = 815607889.5370094
at iteration 6272820 loss = 815607888.6394929
at iteration 6272821 loss = 815607887.7419769
at iteration 6272822 loss = 815607886.844461
at iteration 6272823 loss = 815607885.9469455
at iteration 6272824 loss = 815607885.0494299
at iteration 6272825 loss = 815607884.1519148
at iteration 6272826 loss = 815607883.2544
at iteration 6272827 loss = 815607882.3568854
at iteration 6272828 loss = 815607881.4593714
at iteration 6272829 loss = 815607880.5618572
at iteration 6272830 loss = 815607879.6643436
at iteration 6272831 loss = 815607878.7668307
at iteration 6272832 loss = 815607877.8693175
at iteration 6272833 loss = 815607876.9718046
at iteration 6272834 loss = 815607876.0742918
at iteration 6272835 loss = 815607875.1767794
at iteration 6272836 loss = 815607874.2792677
at iteration 6272837 loss = 815607873.381756
at iteration 6272838 loss = 815607872.4842442
at iteration 6272839 loss = 815607

KeyboardInterrupt: ignored

#**Testing and Evaluating the model**

##**A) Read the test set**

In [202]:
test_data = pd.read_csv("test.csv")
x_df = test_data.loc[:,["MSSubClass","LotArea","OverallQual","OverallCond","YearBuilt","1stFlrSF","2ndFlrSF","GrLivArea","GarageArea","YrSold"]]
x = x_df.fillna(0).values
y = test_data.iloc[:,-1].values

[[2.0000e+01 1.1622e+04 5.0000e+00 ... 8.9600e+02 7.3000e+02 2.0100e+03]
 [2.0000e+01 1.4267e+04 6.0000e+00 ... 1.3290e+03 3.1200e+02 2.0100e+03]
 [6.0000e+01 1.3830e+04 5.0000e+00 ... 1.6290e+03 4.8200e+02 2.0100e+03]
 ...
 [2.0000e+01 2.0000e+04 5.0000e+00 ... 1.2240e+03 5.7600e+02 2.0060e+03]
 [8.5000e+01 1.0441e+04 5.0000e+00 ... 9.7000e+02 0.0000e+00 2.0060e+03]
 [6.0000e+01 9.6270e+03 7.0000e+00 ... 2.0000e+03 6.5000e+02 2.0060e+03]]


##**B) Reading the thetas for the three models**

In [133]:
data1 = pd.read_csv("theta_linear_reg.csv")
theta1 = data1.iloc[-1,:].values

data2 = pd.read_csv("theta_2nd-degree_reg.csv")
theta2 = data2.iloc[-1,:].values

data3 = pd.read_csv("theta_3rd-degree_reg.csv")
theta3 = data3.iloc[-1,:].values


[-182645.438    -25268.27741  121799.1846   262724.6663    23617.7051
  261601.8813   204376.1709    46044.63068  126176.2033    72499.95819
 -182877.9825 ]


##**C) Scalling the testset features**

In [203]:
scal_fact = x_df.max().values
x = x/scal_fact
x_test = x  
y_test = y

x_test1 = np.c_[np.ones(len(x_test)),x_test]
x_test2 = np.c_[np.ones(len(x_test)),x_test,np.square(x_test)]
x_test3 = np.c_[np.ones(len(x_test)),x_test,np.square(x_test),np.power(x_test,3)]

11


##**D) Predicting the results**

In [204]:
y_pred1 = np.matmul(x_test1,theta1)
y_pred2 = np.matmul(x_test2,theta2)
y_pred3 = np.matmul(x_test3,theta3)

print("============================[Linear-regression]=============================")
print(y_pred1)
print("\n\n======================[2nd-order-nonlinear-regression]======================")
print(y_pred2)
print("\n\n======================[3rd-order-nonlinear-regression]======================")
print(y_pred3)


============================[Linear-regression]=============================
[152856.83388633 192156.53657817 179037.43903349 ... 187520.23250196
 112678.49880998 249974.78893317]


======================[2nd-order-nonlinear-regression]======================
[154000.56587868 200390.94747128 198332.39823661 ... 212902.27132698
 147337.04355256 260161.32177193]


======================[3rd-order-nonlinear-regression]======================
[163037.85842995 193579.47763077 209244.11386782 ... 200855.56526531
 158485.50987853 257146.09442735]


##**E) Calculate the loss for each model**

In [205]:
y_test=y_test.reshape(len(y_test),1)
y_pred1=y_pred1.reshape(len(y_pred1),1)
y_pred2=y_pred2.reshape(len(y_pred2),1)
y_pred3=y_pred3.reshape(len(y_pred3),1)

test1_loss = np.sum(np.square(np.subtract(y_pred1,y_test)))
test2_loss = np.sum(np.square(np.subtract(y_pred2,y_test)))
test3_loss = np.sum(np.square(np.subtract(y_pred3,y_test)))

[[2.69623579e+08]
 [1.93436581e+07]
 [2.06683397e+07]
 ...
 [1.00502891e+09]
 [5.21945286e+09]
 [3.87293661e+09]]


##**F) Selecting the best model for the dataset**

In [217]:
print(f"linear regression model:                  loss = {test1_loss}")
print(f"2nd-degree non-linear regression model:   loss = {test2_loss}")
print(f"3rd-degree non-linear regression model:   loss = {test3_loss}")
print("---------------------------------------------------------------------")
if(test1_loss<test2_loss):
  if (test1_loss<test3_loss):
    best_model = "linear regression model"
    best_loss = test1_loss
  elif (test2_loss<test3_loss):
    best_model = "2nd-degree non-linear regression model"
    best_loss = test2_loss
  else: 
    best_model = "3rd-degree non-linear regression model"
    best_loss = test3_loss

print(f"\nthe best model is :                       {best_model}")
print(f"the best loss is :                        {best_loss}")



linear regression model:                  loss = 6772038797017.164
2nd-degree non-linear regression model:   loss = 8503846896004.93
3rd-degree non-linear regression model:   loss = 9338696774769.7
---------------------------------------------------------------------

the best model is :                       linear regression model
the best loss is :                        6772038797017.164
